# Generated by Django 3.2.20 on 2023-07-06 00:28

from django.db import migrations, models
import django.db.models.deletion
import openedx.features.content_tagging.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("oel_tagging", "0003_objecttag_proxies"),
        ("organizations", "0003_historicalorganizationcourse"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosedBlockObjectTag",
            fields=[
                (
                    "objecttag_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="oel_tagging.objecttag",
                    ),
                ),
            ],
            bases=(
                openedx.features.content_tagging.models.BlockObjectTagMixin,
                "oel_tagging.closedobjecttag",
            ),
        ),
        migrations.CreateModel(
            name="ClosedCourseObjectTag",
            fields=[
                (
                    "objecttag_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="oel_tagging.objecttag",
                    ),
                ),
            ],
            bases=(
                openedx.features.content_tagging.models.CourseObjectTagMixin,
                "oel_tagging.closedobjecttag",
            ),
        ),
        migrations.CreateModel(
            name="OpenBlockObjectTag",
            fields=[
                (
                    "objecttag_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="oel_tagging.objecttag",
                    ),
                ),
            ],
            bases=(
                openedx.features.content_tagging.models.BlockObjectTagMixin,
                "oel_tagging.openobjecttag",
            ),
        ),
        migrations.CreateModel(
            name="OpenCourseObjectTag",
            fields=[
                (
                    "objecttag_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="oel_tagging.objecttag",
                    ),
                ),
            ],
            bases=(
                openedx.features.content_tagging.models.CourseObjectTagMixin,
                "oel_tagging.openobjecttag",
            ),
        ),
        migrations.CreateModel(
            name="TaxonomyOrg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rel_type",
                    models.CharField(
                        choices=[("OWN", "owner")], default="OWN", max_length=3
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oel_tagging.taxonomy",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="taxonomyorg",
            index=models.Index(
                fields=["taxonomy", "rel_type"], name="content_tag_taxonom_b04dd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomyorg",
            index=models.Index(
                fields=["taxonomy", "rel_type", "org"],
                name="content_tag_taxonom_70d60b_idx",
            ),
        ),
    ]
