# Generated by Django 4.2.10 on 2024-03-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGraphCourseDump',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('course_overviews.courseoverview',),
        ),
    ]
