# Generated by Django 2.2.24 on 2021-07-24 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_libraries', '0006_auto_20210615_1916'),
        ('content_libraries', '0005_contentlibraryblockimporttask'),
    ]

    operations = [
    ]
